apiVersion: v1
kind: Secret
metadata:
  name: my-devops-app-secret
type: Opaque
data:
  DATABASE_NAME: db:sqlite3
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXdjMmkyKjZeMTckOSF1Kyh1NjZAcV9yZykrK24xeC1eKDAtJDN5ejJmKG49Xy1vKjc9